// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9FXDCrUSoo7qR3J6TEXeTof2OUbXt3iM',
    appId: '1:298844365494:web:326c07031ba0c63904bc17',
    messagingSenderId: '298844365494',
    projectId: 'flutter-proyects-e66fd',
    authDomain: 'flutter-proyects-e66fd.firebaseapp.com',
    storageBucket: 'flutter-proyects-e66fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqh1mpqcyrz05iFCa-Z4fXpzr_Q8w3n2Q',
    appId: '1:298844365494:android:3b0ce01824d7f9e604bc17',
    messagingSenderId: '298844365494',
    projectId: 'flutter-proyects-e66fd',
    storageBucket: 'flutter-proyects-e66fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM6fk4kgGjwoOmCwonux2G7NBC7xlghcc',
    appId: '1:298844365494:ios:dfa8f32f03fa432304bc17',
    messagingSenderId: '298844365494',
    projectId: 'flutter-proyects-e66fd',
    storageBucket: 'flutter-proyects-e66fd.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM6fk4kgGjwoOmCwonux2G7NBC7xlghcc',
    appId: '1:298844365494:ios:dfa8f32f03fa432304bc17',
    messagingSenderId: '298844365494',
    projectId: 'flutter-proyects-e66fd',
    storageBucket: 'flutter-proyects-e66fd.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9FXDCrUSoo7qR3J6TEXeTof2OUbXt3iM',
    appId: '1:298844365494:web:4cef3d110bf847b204bc17',
    messagingSenderId: '298844365494',
    projectId: 'flutter-proyects-e66fd',
    authDomain: 'flutter-proyects-e66fd.firebaseapp.com',
    storageBucket: 'flutter-proyects-e66fd.firebasestorage.app',
  );

}